apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aso 
  namespace: azureserviceoperator-system 
spec:
  interval: 1m
  url: https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts 
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aso2
  namespace: azureserviceoperator-system
spec:
  releaseName: aso2 
  interval: 5m
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: azure-service-operator 
      sourceRef:
        kind: HelmRepository
        name: aso 
        namespace: azureserviceoperator-system 
      interval: 1m
  values:
    crdPattern: 'resources.azure.com/*;containerservice.azure.com/*;keyvault.azure.com/*;managedidentity.azure.com/*;eventhub.azure.com/*'
