apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager 
  namespace: flux-system 
spec:
  interval: 1m
  url: https://charts.jetstack.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager 
  namespace: flux-system 
spec:
  releaseName: cert-manager 
  interval: 5m
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: cert-manager 
      sourceRef:
        kind: HelmRepository
        name: cert-manager 
        namespace: flux-system 
      interval: 1m